server:
  port: 8888

spring:
  application:
    name: eduSystem
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.242.214:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: acd270e56ec246ae

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wlh.springcloud.entity    # 所有Entity别名类所在包
